apiVersion: v1
kind: Service
metadata:
  name: herald
  namespace: cwb
  labels:
    app: herald
spec:
  type: ClusterIP
  selector:
    app: herald
  ports:
    - name: http
      port: 8099
      targetPort: http
      protocol: TCP
